#
# affy/sdk/translation/util-package/Makefile ---
#
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs

# classic
#$(call sdk_define_exe,apt-util-package,apt-util-package.cpp)
#$(call sdk_define_install_exe,apt-util-package)

sdk_cpp_cflags+=-I..

include ${sdk_makefile_post}
