#
# affy/sdk/chipstream/apt-copynumber-consanguine/Makefile ---
#
# $Id: Makefile,v 1.2 2009-04-22 21:13:54 awilli Exp $
#

#
sdk_root:=../..
include ${sdk_root}/Makefile.defs
#
# classic
$(call sdk_define_exe,apt-copynumber-familial,apt-copynumber-familial.cpp)

include ${sdk_makefile_post}
