Affymetrix Power Tools: ScaleIntensities Class Reference
ScaleIntensities Class Reference
Class for scaling cel intensities.
#include <ScaleIntensities.h>