Affymetrix Power Tools: GcCorrection Class Reference
GcCorrection Class Reference
Class for doing an adjustment based on the median intensity of probes with similar GC content.
#include <GcCorrection.h>